# Generated by Django 5.1.4 on 2026-07-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['country'], name='analytics_v_country_361d9a_idx'), models.Index(fields=['browser'], name='analytics_v_browser_aad083_idx'), models.Index(fields=['visit_time'], name='analytics_v_visit_t_61c9a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['path'], name='analytics_p_path_3fa0ca_idx')],
            },
        ),
    ]
